# Application class with value 10 
? class=false, value=10, tag=2, lvt=1
0x21 0x0A
# Application class with value 255 
? class=false, value=255, tag=2, lvt=1
0x21 0xFF
# Application class with value 100 
? class=false, value=100, tag=2, lvt=1
0x21 0x64
# Application class with value 300 
? class=false, value=300, tag=2, lvt=2
0x22 0x01 0x2c
# Application class with value 65535 
? class=false, value=65535, tag=2, lvt=2
0x22 0xFF 0xFF
# Application class with value 300000 
? class=false, value=300000, tag=2, lvt=4
0x24 0x00 0x04 0x93 0xe0
# no final newline